# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/PyCQA/prospector
    rev: 1.3.1 # The version of Prospector to use, at least 1.1.7
    hooks:
    -   id: prospector
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        log_file: 1

