output-format: grouped

strictness: high
doc-warnings: true
test-warnings: false
max-line-length: 120

ignore-paths:
  - docs/
  - venv/
  - data/
  - site/

frosted:
  run: false

pyroma:
  run: false

mypy:
  run: false
  options:
    ignore-missing-imports: true
    follow-imports: skip

pylint:
  run: false
  disable:
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args

pep8:
  run: true
  full: true
  disable:
    - E126
#
pep257:
  run: false
  disable:
    - D100
    - D101
    - D102
    - D103
    - D205
    - D400
    - D401

pyflake:
  run: false