version: "3"

services: 
    xeo_db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=xeo_users
            - POSTGRES_USER=anuj
            - POSTGRES_PASSWORD=password
    xeo_web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports: 
            - "8000:8000"
        depends_on: 
            - xeo_db
        restart: always
