site_name: User Microservice
site_url: http://localhost:8001
nav:
    - Welcome: index.md
    - Development Life Cycle: sdlc.md
    - Microservices: microservice.md
    - Unit Testing: unit-testing.md
    - About: about.md
    - Reference: reference.md
    - Thank-you: thank-you.md
theme: material
