# Generated by Django 3.2.5 on 2021-07-09 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
          model_name='userinfo',
          name='id'
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
