# Generated by Django 3.2.5 on 2021-07-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_userinfo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='info',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='service.user'),
            preserve_default=False,
        ),
    ]
